### PR TITLE
FTR-Fix finished fixing sabotaged code for Team3

### PR DESCRIPTION
**Pull request by whe1123**

### CODE REVIEW

**Review by zaidisyed1991 — APPROVED** [review]
consume() looks good
attack() looks good
eatCookie() looks good

**Review by DanXu007 — APPROVED** [review]
PacManInRange() looks good
GhostInRange() looks good
MapAttack() looks good

**Comment by amanthanvi** [comment]
PacManInRange() looks good
GhostInRange() looks good
MapAttack() looks good

All tests passing looks good. Approved

**Review by 1onQ — APPROVED** [review]
Approve
PacMan.move()
Ghost.move()
Map.getLoc()

**Pull request merged**
